### ISSUE TITLE
Edge Embedding in Dynamic Graph

### ISSUE THREAD

**Issue by Hannibal046** [shangqing-liu/CCSD-benchmark-for-code-summarization#2]
Hello!
Thanks for the great paper of code summarization.
I have a question about the edge embedding in the dynamic graph. Since you want to create a fully-connected graph, what is the embedding of arbitrary node pairs? Does this depend on the node type of every node? or derived from shortest part in the graph?
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/38466901/122666451-d8ca9780-d1df-11eb-8836-b02b3beb9ec3.png">

**Comment by shangqing-liu** [comment]
Hi,

Thanks for your attention to our work.  The initial node embeddings of the
dynamic graphs are the same as the static graphs i.e., the last hidden
states of BiLSTM used for node initial representation.

Regards
